---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: trendoperators.container-security.trendmicro.com
spec:
  group: container-security.trendmicro.com
  names:
    kind: TrendOperator
    listKind: TrendOperatorList
    plural: trendoperators
    singular: trendoperator
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TrendOperator is the Schema for the trendoperators API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              affinity:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              cloudOne:
                properties:
                  apiKey:
                    type: string
                  endpoint:
                    type: string
                  exclusion:
                    properties:
                      namespaces:
                        items:
                          type: string
                        type: array
                      osNsPrefixes:
                        items:
                          type: string
                        type: array
                    type: object
                  inventoryCollection:
                    properties:
                      enabled:
                        type: boolean
                    type: object
                  malwareScanning:
                    properties:
                      enabled:
                        type: boolean
                      excludedPaths:
                        items:
                          type: string
                        type: array
                      scanTimeoutSeconds:
                        type: integer
                    type: object
                  runtimeSecurity:
                    properties:
                      enabled:
                        type: boolean
                    type: object
                  vulnerabilityScanning:
                    properties:
                      enabled:
                        type: boolean
                    type: object
                required:
                - apiKey
                - endpoint
                type: object
              fullnameOverride:
                type: string
              image:
                properties:
                  pullPolicy:
                    type: string
                  repository:
                    type: string
                  tag:
                    type: string
                type: object
              imagePullSecrets:
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                type: array
              nameOverride:
                type: string
              nodeSelector:
                additionalProperties:
                  type: string
                type: object
              podAnnotations:
                additionalProperties:
                  type: string
                type: object
              podLabels:
                additionalProperties:
                  type: string
                type: object
              podSecurityContext:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              replicaCount:
                type: integer
              resources:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              securityContext:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              serviceAccount:
                properties:
                  annotations:
                    additionalProperties:
                      type: string
                    type: object
                  automount:
                    type: boolean
                  create:
                    type: boolean
                  enabled:
                    type: boolean
                  name:
                    type: string
                type: object
              volumeMounts:
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                type: array
              volumes:
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                type: array
            required:
            - cloudOne
            type: object
          status:
            description: Status defines the observed state of TrendOperator
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
